services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn api.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"  
    environment:
      - DJANGO_SETTINGS_MODULE=api.settings
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
      - static_data:/app/staticfiles  # Mount static_data to /app/staticfiles
      - media_data:/app/media  # Mount media_data to /app/media
      - db_data:/app/db.sqlite3  # Mount db_data to /app/db.sqlite3
    networks:
      - my-network

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf  # Mount Nginx config
      - static_data:/app/staticfiles  # Mount static_data to /app/staticfiles
      - media_data:/app/media  # Mount media_data to /app/media
    depends_on:
      - web
    networks:
      - my-network

volumes:
  static_data:  # Shared volume for static files
  media_data:   # Shared volume for media files
  db_data:      # Shared volume for the SQLite database

networks:
  my-network:   # Custom network for communication between containers