services:
  db:
    image: postgres:14-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: securepassword
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - my-network

  web:
    image: afripoint/cvms_backend_conversion-web:latest
    container_name: web
    env_file:
      - .env
    volumes:
      - staticfiles:/app/staticfiles
      - media:/app/media
    depends_on:
      - db
    command: gunicorn --bind 0.0.0.0:8000 --workers 3 --timeout 180 api.wsgi:application
    networks:
      - my-network

  nginx:
    image: afripoint/cvms_backend_conversion-nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - staticfiles:/app/staticfiles
      - media:/app/media
    depends_on:
      - web
    networks:
      - my-network

volumes:
  db_data:
  staticfiles:
  media:

networks:
  my-network:
