services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command:  
      - gunicorn
      - api.wsgi:application
      - --bind
      - 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env 
    environment:
      DJANGO_SETTINGS_MODULE: api.settings 
      PYTHONUNBUFFERED: 1 
    volumes:
      - .:/app  
      - static_data:/app/staticfiles  
      - media_data:/app/media  
      - db_data:/app/db.sqlite3  
    networks:
      - my-network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf  
      - static_data:/app/staticfiles  
      - media_data:/app/media  
    depends_on:
      - web
    networks:
      - my-network

volumes:
  static_data:  
  media_data:   
  db_data:     

networks:
  my-network: