name: Build, Test, Scan, and Deploy

on:
  push:
    branches:
      - DevOps-CVM

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          DATABASE_ENGINE: ${{ secrets.DATABASE_ENGINE || 'django.db.backends.sqlite3' }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME || 'db.sqlite3' }}
          ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS || 'localhost,127.0.0.1,0.0.0.0' }}
          EMAIL_HOST: ${{ secrets.EMAIL_HOST || 'smtp.gmail.com' }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT || '587' }}
          EMAIL_USE_TLS: ${{ secrets.EMAIL_USE_TLS || 'True' }}
          EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
          EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
          DEFAULT_FROM_EMAIL: ${{ secrets.DEFAULT_FROM_EMAIL }}
          DEBUG: ${{ secrets.DEBUG || 'True' }}
          DJANGO_SETTINGS_MODULE: api.settings
        run: python manage.py test

  code-scan:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Bandit (security scan)
        run: |
          pip install bandit
          bandit -r .

      - name: Run Flake8 (code quality scan)
        run: |
          pip install flake8
          flake8 .

  build-and-push:
    runs-on: ubuntu-latest
    needs: code-scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push web service image
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          DATABASE_ENGINE: ${{ secrets.DATABASE_ENGINE || 'django.db.backends.sqlite3' }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME || 'db.sqlite3' }}
          ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS || 'localhost,127.0.0.1,0.0.0.0' }}
          EMAIL_HOST: ${{ secrets.EMAIL_HOST || 'smtp.gmail.com' }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT || '587' }}
          EMAIL_USE_TLS: ${{ secrets.EMAIL_USE_TLS || 'True' }}
          EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
          EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
          DEFAULT_FROM_EMAIL: ${{ secrets.DEFAULT_FROM_EMAIL }}
          DEBUG: ${{ secrets.DEBUG || 'True' }}
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/cvms_backend_conversion-web:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cvms_backend_conversion-web:latest

      - name: Build and push Nginx service image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/cvms_backend_conversion-nginx:latest ./nginx
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cvms_backend_conversion-nginx:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} '
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/cvms_backend_conversion-web:latest
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/cvms_backend_conversion-nginx:latest
            docker-compose down
            docker-compose up -d
          '
